// Code generated by go-swagger; DO NOT EDIT.

package customer_shipping_address

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetCustomerShippingAddressParams creates a new GetCustomerShippingAddressParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetCustomerShippingAddressParams() *GetCustomerShippingAddressParams {
	return &GetCustomerShippingAddressParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetCustomerShippingAddressParamsWithTimeout creates a new GetCustomerShippingAddressParams object
// with the ability to set a timeout on a request.
func NewGetCustomerShippingAddressParamsWithTimeout(timeout time.Duration) *GetCustomerShippingAddressParams {
	return &GetCustomerShippingAddressParams{
		timeout: timeout,
	}
}

// NewGetCustomerShippingAddressParamsWithContext creates a new GetCustomerShippingAddressParams object
// with the ability to set a context for a request.
func NewGetCustomerShippingAddressParamsWithContext(ctx context.Context) *GetCustomerShippingAddressParams {
	return &GetCustomerShippingAddressParams{
		Context: ctx,
	}
}

// NewGetCustomerShippingAddressParamsWithHTTPClient creates a new GetCustomerShippingAddressParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetCustomerShippingAddressParamsWithHTTPClient(client *http.Client) *GetCustomerShippingAddressParams {
	return &GetCustomerShippingAddressParams{
		HTTPClient: client,
	}
}

/*
GetCustomerShippingAddressParams contains all the parameters to send to the API endpoint

	for the get customer shipping address operation.

	Typically these are written to a http.Request.
*/
type GetCustomerShippingAddressParams struct {

	/* CustomerID.

	   The Id of a Customer.
	*/
	CustomerID string

	/* ProfileID.

	   The Id of a profile containing user specific TMS configuration.
	*/
	ProfileID *string

	/* ShippingAddressID.

	   The Id of a shipping address.
	*/
	ShippingAddressID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get customer shipping address params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetCustomerShippingAddressParams) WithDefaults() *GetCustomerShippingAddressParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get customer shipping address params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetCustomerShippingAddressParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get customer shipping address params
func (o *GetCustomerShippingAddressParams) WithTimeout(timeout time.Duration) *GetCustomerShippingAddressParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get customer shipping address params
func (o *GetCustomerShippingAddressParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get customer shipping address params
func (o *GetCustomerShippingAddressParams) WithContext(ctx context.Context) *GetCustomerShippingAddressParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get customer shipping address params
func (o *GetCustomerShippingAddressParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get customer shipping address params
func (o *GetCustomerShippingAddressParams) WithHTTPClient(client *http.Client) *GetCustomerShippingAddressParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get customer shipping address params
func (o *GetCustomerShippingAddressParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithCustomerID adds the customerID to the get customer shipping address params
func (o *GetCustomerShippingAddressParams) WithCustomerID(customerID string) *GetCustomerShippingAddressParams {
	o.SetCustomerID(customerID)
	return o
}

// SetCustomerID adds the customerId to the get customer shipping address params
func (o *GetCustomerShippingAddressParams) SetCustomerID(customerID string) {
	o.CustomerID = customerID
}

// WithProfileID adds the profileID to the get customer shipping address params
func (o *GetCustomerShippingAddressParams) WithProfileID(profileID *string) *GetCustomerShippingAddressParams {
	o.SetProfileID(profileID)
	return o
}

// SetProfileID adds the profileId to the get customer shipping address params
func (o *GetCustomerShippingAddressParams) SetProfileID(profileID *string) {
	o.ProfileID = profileID
}

// WithShippingAddressID adds the shippingAddressID to the get customer shipping address params
func (o *GetCustomerShippingAddressParams) WithShippingAddressID(shippingAddressID string) *GetCustomerShippingAddressParams {
	o.SetShippingAddressID(shippingAddressID)
	return o
}

// SetShippingAddressID adds the shippingAddressId to the get customer shipping address params
func (o *GetCustomerShippingAddressParams) SetShippingAddressID(shippingAddressID string) {
	o.ShippingAddressID = shippingAddressID
}

// WriteToRequest writes these params to a swagger request
func (o *GetCustomerShippingAddressParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param customerId
	if err := r.SetPathParam("customerId", o.CustomerID); err != nil {
		return err
	}

	if o.ProfileID != nil {

		// header param profile-id
		if err := r.SetHeaderParam("profile-id", *o.ProfileID); err != nil {
			return err
		}
	}

	// path param shippingAddressId
	if err := r.SetPathParam("shippingAddressId", o.ShippingAddressID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
