// Code generated by go-swagger; DO NOT EDIT.

package payment_instrument

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"encoding/json"
	"fmt"
	"io"
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// DeletePaymentInstrumentReader is a Reader for the DeletePaymentInstrument structure.
type DeletePaymentInstrumentReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DeletePaymentInstrumentReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 204:
		result := NewDeletePaymentInstrumentNoContent()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 403:
		result := NewDeletePaymentInstrumentForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewDeletePaymentInstrumentNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 410:
		result := NewDeletePaymentInstrumentGone()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 424:
		result := NewDeletePaymentInstrumentFailedDependency()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewDeletePaymentInstrumentInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[DELETE /tms/v1/paymentinstruments/{paymentInstrumentId}] deletePaymentInstrument", response, response.Code())
	}
}

// NewDeletePaymentInstrumentNoContent creates a DeletePaymentInstrumentNoContent with default headers values
func NewDeletePaymentInstrumentNoContent() *DeletePaymentInstrumentNoContent {
	return &DeletePaymentInstrumentNoContent{}
}

/*
DeletePaymentInstrumentNoContent describes a response with status code 204, with default header values.

The request is fulfilled but does not need to return a body
*/
type DeletePaymentInstrumentNoContent struct {

	/* A globally unique Id associated with your request.
	 */
	UniqueTransactionID string

	/* The mandatory correlation Id passed by upstream (calling) system.
	 */
	VcCorrelationID string
}

// IsSuccess returns true when this delete payment instrument no content response has a 2xx status code
func (o *DeletePaymentInstrumentNoContent) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this delete payment instrument no content response has a 3xx status code
func (o *DeletePaymentInstrumentNoContent) IsRedirect() bool {
	return false
}

// IsClientError returns true when this delete payment instrument no content response has a 4xx status code
func (o *DeletePaymentInstrumentNoContent) IsClientError() bool {
	return false
}

// IsServerError returns true when this delete payment instrument no content response has a 5xx status code
func (o *DeletePaymentInstrumentNoContent) IsServerError() bool {
	return false
}

// IsCode returns true when this delete payment instrument no content response a status code equal to that given
func (o *DeletePaymentInstrumentNoContent) IsCode(code int) bool {
	return code == 204
}

// Code gets the status code for the delete payment instrument no content response
func (o *DeletePaymentInstrumentNoContent) Code() int {
	return 204
}

func (o *DeletePaymentInstrumentNoContent) Error() string {
	return fmt.Sprintf("[DELETE /tms/v1/paymentinstruments/{paymentInstrumentId}][%d] deletePaymentInstrumentNoContent", 204)
}

func (o *DeletePaymentInstrumentNoContent) String() string {
	return fmt.Sprintf("[DELETE /tms/v1/paymentinstruments/{paymentInstrumentId}][%d] deletePaymentInstrumentNoContent", 204)
}

func (o *DeletePaymentInstrumentNoContent) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// hydrates response header uniqueTransactionID
	hdrUniqueTransactionID := response.GetHeader("uniqueTransactionID")

	if hdrUniqueTransactionID != "" {
		o.UniqueTransactionID = hdrUniqueTransactionID
	}

	// hydrates response header v-c-correlation-id
	hdrVcCorrelationID := response.GetHeader("v-c-correlation-id")

	if hdrVcCorrelationID != "" {
		o.VcCorrelationID = hdrVcCorrelationID
	}

	return nil
}

// NewDeletePaymentInstrumentForbidden creates a DeletePaymentInstrumentForbidden with default headers values
func NewDeletePaymentInstrumentForbidden() *DeletePaymentInstrumentForbidden {
	return &DeletePaymentInstrumentForbidden{}
}

/*
DeletePaymentInstrumentForbidden describes a response with status code 403, with default header values.

Forbidden: e.g. The profile might not have permission to perform the operation.
*/
type DeletePaymentInstrumentForbidden struct {

	/* A globally unique Id associated with your request.
	 */
	UniqueTransactionID string

	/* The mandatory correlation Id passed by upstream (calling) system.
	 */
	VcCorrelationID string

	Payload *DeletePaymentInstrumentForbiddenBody
}

// IsSuccess returns true when this delete payment instrument forbidden response has a 2xx status code
func (o *DeletePaymentInstrumentForbidden) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this delete payment instrument forbidden response has a 3xx status code
func (o *DeletePaymentInstrumentForbidden) IsRedirect() bool {
	return false
}

// IsClientError returns true when this delete payment instrument forbidden response has a 4xx status code
func (o *DeletePaymentInstrumentForbidden) IsClientError() bool {
	return true
}

// IsServerError returns true when this delete payment instrument forbidden response has a 5xx status code
func (o *DeletePaymentInstrumentForbidden) IsServerError() bool {
	return false
}

// IsCode returns true when this delete payment instrument forbidden response a status code equal to that given
func (o *DeletePaymentInstrumentForbidden) IsCode(code int) bool {
	return code == 403
}

// Code gets the status code for the delete payment instrument forbidden response
func (o *DeletePaymentInstrumentForbidden) Code() int {
	return 403
}

func (o *DeletePaymentInstrumentForbidden) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[DELETE /tms/v1/paymentinstruments/{paymentInstrumentId}][%d] deletePaymentInstrumentForbidden %s", 403, payload)
}

func (o *DeletePaymentInstrumentForbidden) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[DELETE /tms/v1/paymentinstruments/{paymentInstrumentId}][%d] deletePaymentInstrumentForbidden %s", 403, payload)
}

func (o *DeletePaymentInstrumentForbidden) GetPayload() *DeletePaymentInstrumentForbiddenBody {
	return o.Payload
}

func (o *DeletePaymentInstrumentForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// hydrates response header uniqueTransactionID
	hdrUniqueTransactionID := response.GetHeader("uniqueTransactionID")

	if hdrUniqueTransactionID != "" {
		o.UniqueTransactionID = hdrUniqueTransactionID
	}

	// hydrates response header v-c-correlation-id
	hdrVcCorrelationID := response.GetHeader("v-c-correlation-id")

	if hdrVcCorrelationID != "" {
		o.VcCorrelationID = hdrVcCorrelationID
	}

	o.Payload = new(DeletePaymentInstrumentForbiddenBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewDeletePaymentInstrumentNotFound creates a DeletePaymentInstrumentNotFound with default headers values
func NewDeletePaymentInstrumentNotFound() *DeletePaymentInstrumentNotFound {
	return &DeletePaymentInstrumentNotFound{}
}

/*
DeletePaymentInstrumentNotFound describes a response with status code 404, with default header values.

Token Not Found. The Id may not exist or was entered incorrectly.
*/
type DeletePaymentInstrumentNotFound struct {

	/* A globally unique Id associated with your request.
	 */
	UniqueTransactionID string

	/* The mandatory correlation Id passed by upstream (calling) system.
	 */
	VcCorrelationID string

	Payload *DeletePaymentInstrumentNotFoundBody
}

// IsSuccess returns true when this delete payment instrument not found response has a 2xx status code
func (o *DeletePaymentInstrumentNotFound) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this delete payment instrument not found response has a 3xx status code
func (o *DeletePaymentInstrumentNotFound) IsRedirect() bool {
	return false
}

// IsClientError returns true when this delete payment instrument not found response has a 4xx status code
func (o *DeletePaymentInstrumentNotFound) IsClientError() bool {
	return true
}

// IsServerError returns true when this delete payment instrument not found response has a 5xx status code
func (o *DeletePaymentInstrumentNotFound) IsServerError() bool {
	return false
}

// IsCode returns true when this delete payment instrument not found response a status code equal to that given
func (o *DeletePaymentInstrumentNotFound) IsCode(code int) bool {
	return code == 404
}

// Code gets the status code for the delete payment instrument not found response
func (o *DeletePaymentInstrumentNotFound) Code() int {
	return 404
}

func (o *DeletePaymentInstrumentNotFound) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[DELETE /tms/v1/paymentinstruments/{paymentInstrumentId}][%d] deletePaymentInstrumentNotFound %s", 404, payload)
}

func (o *DeletePaymentInstrumentNotFound) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[DELETE /tms/v1/paymentinstruments/{paymentInstrumentId}][%d] deletePaymentInstrumentNotFound %s", 404, payload)
}

func (o *DeletePaymentInstrumentNotFound) GetPayload() *DeletePaymentInstrumentNotFoundBody {
	return o.Payload
}

func (o *DeletePaymentInstrumentNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// hydrates response header uniqueTransactionID
	hdrUniqueTransactionID := response.GetHeader("uniqueTransactionID")

	if hdrUniqueTransactionID != "" {
		o.UniqueTransactionID = hdrUniqueTransactionID
	}

	// hydrates response header v-c-correlation-id
	hdrVcCorrelationID := response.GetHeader("v-c-correlation-id")

	if hdrVcCorrelationID != "" {
		o.VcCorrelationID = hdrVcCorrelationID
	}

	o.Payload = new(DeletePaymentInstrumentNotFoundBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewDeletePaymentInstrumentGone creates a DeletePaymentInstrumentGone with default headers values
func NewDeletePaymentInstrumentGone() *DeletePaymentInstrumentGone {
	return &DeletePaymentInstrumentGone{}
}

/*
DeletePaymentInstrumentGone describes a response with status code 410, with default header values.

Token Not Available. The token has been deleted.
*/
type DeletePaymentInstrumentGone struct {

	/* A globally unique Id associated with your request.
	 */
	UniqueTransactionID string

	/* The mandatory correlation Id passed by upstream (calling) system.
	 */
	VcCorrelationID string

	Payload *DeletePaymentInstrumentGoneBody
}

// IsSuccess returns true when this delete payment instrument gone response has a 2xx status code
func (o *DeletePaymentInstrumentGone) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this delete payment instrument gone response has a 3xx status code
func (o *DeletePaymentInstrumentGone) IsRedirect() bool {
	return false
}

// IsClientError returns true when this delete payment instrument gone response has a 4xx status code
func (o *DeletePaymentInstrumentGone) IsClientError() bool {
	return true
}

// IsServerError returns true when this delete payment instrument gone response has a 5xx status code
func (o *DeletePaymentInstrumentGone) IsServerError() bool {
	return false
}

// IsCode returns true when this delete payment instrument gone response a status code equal to that given
func (o *DeletePaymentInstrumentGone) IsCode(code int) bool {
	return code == 410
}

// Code gets the status code for the delete payment instrument gone response
func (o *DeletePaymentInstrumentGone) Code() int {
	return 410
}

func (o *DeletePaymentInstrumentGone) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[DELETE /tms/v1/paymentinstruments/{paymentInstrumentId}][%d] deletePaymentInstrumentGone %s", 410, payload)
}

func (o *DeletePaymentInstrumentGone) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[DELETE /tms/v1/paymentinstruments/{paymentInstrumentId}][%d] deletePaymentInstrumentGone %s", 410, payload)
}

func (o *DeletePaymentInstrumentGone) GetPayload() *DeletePaymentInstrumentGoneBody {
	return o.Payload
}

func (o *DeletePaymentInstrumentGone) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// hydrates response header uniqueTransactionID
	hdrUniqueTransactionID := response.GetHeader("uniqueTransactionID")

	if hdrUniqueTransactionID != "" {
		o.UniqueTransactionID = hdrUniqueTransactionID
	}

	// hydrates response header v-c-correlation-id
	hdrVcCorrelationID := response.GetHeader("v-c-correlation-id")

	if hdrVcCorrelationID != "" {
		o.VcCorrelationID = hdrVcCorrelationID
	}

	o.Payload = new(DeletePaymentInstrumentGoneBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewDeletePaymentInstrumentFailedDependency creates a DeletePaymentInstrumentFailedDependency with default headers values
func NewDeletePaymentInstrumentFailedDependency() *DeletePaymentInstrumentFailedDependency {
	return &DeletePaymentInstrumentFailedDependency{}
}

/*
DeletePaymentInstrumentFailedDependency describes a response with status code 424, with default header values.

Failed Dependency: e.g. The profile represented by the profile-id may not exist or the profile-id was entered incorrectly.
*/
type DeletePaymentInstrumentFailedDependency struct {

	/* A globally unique Id associated with your request.
	 */
	UniqueTransactionID string

	/* The mandatory correlation Id passed by upstream (calling) system.
	 */
	VcCorrelationID string

	Payload *DeletePaymentInstrumentFailedDependencyBody
}

// IsSuccess returns true when this delete payment instrument failed dependency response has a 2xx status code
func (o *DeletePaymentInstrumentFailedDependency) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this delete payment instrument failed dependency response has a 3xx status code
func (o *DeletePaymentInstrumentFailedDependency) IsRedirect() bool {
	return false
}

// IsClientError returns true when this delete payment instrument failed dependency response has a 4xx status code
func (o *DeletePaymentInstrumentFailedDependency) IsClientError() bool {
	return true
}

// IsServerError returns true when this delete payment instrument failed dependency response has a 5xx status code
func (o *DeletePaymentInstrumentFailedDependency) IsServerError() bool {
	return false
}

// IsCode returns true when this delete payment instrument failed dependency response a status code equal to that given
func (o *DeletePaymentInstrumentFailedDependency) IsCode(code int) bool {
	return code == 424
}

// Code gets the status code for the delete payment instrument failed dependency response
func (o *DeletePaymentInstrumentFailedDependency) Code() int {
	return 424
}

func (o *DeletePaymentInstrumentFailedDependency) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[DELETE /tms/v1/paymentinstruments/{paymentInstrumentId}][%d] deletePaymentInstrumentFailedDependency %s", 424, payload)
}

func (o *DeletePaymentInstrumentFailedDependency) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[DELETE /tms/v1/paymentinstruments/{paymentInstrumentId}][%d] deletePaymentInstrumentFailedDependency %s", 424, payload)
}

func (o *DeletePaymentInstrumentFailedDependency) GetPayload() *DeletePaymentInstrumentFailedDependencyBody {
	return o.Payload
}

func (o *DeletePaymentInstrumentFailedDependency) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// hydrates response header uniqueTransactionID
	hdrUniqueTransactionID := response.GetHeader("uniqueTransactionID")

	if hdrUniqueTransactionID != "" {
		o.UniqueTransactionID = hdrUniqueTransactionID
	}

	// hydrates response header v-c-correlation-id
	hdrVcCorrelationID := response.GetHeader("v-c-correlation-id")

	if hdrVcCorrelationID != "" {
		o.VcCorrelationID = hdrVcCorrelationID
	}

	o.Payload = new(DeletePaymentInstrumentFailedDependencyBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewDeletePaymentInstrumentInternalServerError creates a DeletePaymentInstrumentInternalServerError with default headers values
func NewDeletePaymentInstrumentInternalServerError() *DeletePaymentInstrumentInternalServerError {
	return &DeletePaymentInstrumentInternalServerError{}
}

/*
DeletePaymentInstrumentInternalServerError describes a response with status code 500, with default header values.

Unexpected error.
*/
type DeletePaymentInstrumentInternalServerError struct {

	/* A globally unique Id associated with your request.
	 */
	UniqueTransactionID string

	/* The mandatory correlation Id passed by upstream (calling) system.
	 */
	VcCorrelationID string

	Payload *DeletePaymentInstrumentInternalServerErrorBody
}

// IsSuccess returns true when this delete payment instrument internal server error response has a 2xx status code
func (o *DeletePaymentInstrumentInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this delete payment instrument internal server error response has a 3xx status code
func (o *DeletePaymentInstrumentInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this delete payment instrument internal server error response has a 4xx status code
func (o *DeletePaymentInstrumentInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this delete payment instrument internal server error response has a 5xx status code
func (o *DeletePaymentInstrumentInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this delete payment instrument internal server error response a status code equal to that given
func (o *DeletePaymentInstrumentInternalServerError) IsCode(code int) bool {
	return code == 500
}

// Code gets the status code for the delete payment instrument internal server error response
func (o *DeletePaymentInstrumentInternalServerError) Code() int {
	return 500
}

func (o *DeletePaymentInstrumentInternalServerError) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[DELETE /tms/v1/paymentinstruments/{paymentInstrumentId}][%d] deletePaymentInstrumentInternalServerError %s", 500, payload)
}

func (o *DeletePaymentInstrumentInternalServerError) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[DELETE /tms/v1/paymentinstruments/{paymentInstrumentId}][%d] deletePaymentInstrumentInternalServerError %s", 500, payload)
}

func (o *DeletePaymentInstrumentInternalServerError) GetPayload() *DeletePaymentInstrumentInternalServerErrorBody {
	return o.Payload
}

func (o *DeletePaymentInstrumentInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// hydrates response header uniqueTransactionID
	hdrUniqueTransactionID := response.GetHeader("uniqueTransactionID")

	if hdrUniqueTransactionID != "" {
		o.UniqueTransactionID = hdrUniqueTransactionID
	}

	// hydrates response header v-c-correlation-id
	hdrVcCorrelationID := response.GetHeader("v-c-correlation-id")

	if hdrVcCorrelationID != "" {
		o.VcCorrelationID = hdrVcCorrelationID
	}

	o.Payload = new(DeletePaymentInstrumentInternalServerErrorBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

/*
DeletePaymentInstrumentFailedDependencyBody delete payment instrument failed dependency body
swagger:model DeletePaymentInstrumentFailedDependencyBody
*/
type DeletePaymentInstrumentFailedDependencyBody struct {

	// errors
	// Read Only: true
	Errors []*DeletePaymentInstrumentFailedDependencyBodyErrorsItems0 `json:"errors"`
}

// Validate validates this delete payment instrument failed dependency body
func (o *DeletePaymentInstrumentFailedDependencyBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateErrors(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *DeletePaymentInstrumentFailedDependencyBody) validateErrors(formats strfmt.Registry) error {
	if swag.IsZero(o.Errors) { // not required
		return nil
	}

	for i := 0; i < len(o.Errors); i++ {
		if swag.IsZero(o.Errors[i]) { // not required
			continue
		}

		if o.Errors[i] != nil {
			if err := o.Errors[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("deletePaymentInstrumentFailedDependency" + "." + "errors" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("deletePaymentInstrumentFailedDependency" + "." + "errors" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// ContextValidate validate this delete payment instrument failed dependency body based on the context it is used
func (o *DeletePaymentInstrumentFailedDependencyBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := o.contextValidateErrors(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *DeletePaymentInstrumentFailedDependencyBody) contextValidateErrors(ctx context.Context, formats strfmt.Registry) error {

	if err := validate.ReadOnly(ctx, "deletePaymentInstrumentFailedDependency"+"."+"errors", "body", []*DeletePaymentInstrumentFailedDependencyBodyErrorsItems0(o.Errors)); err != nil {
		return err
	}

	for i := 0; i < len(o.Errors); i++ {

		if o.Errors[i] != nil {

			if swag.IsZero(o.Errors[i]) { // not required
				return nil
			}

			if err := o.Errors[i].ContextValidate(ctx, formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("deletePaymentInstrumentFailedDependency" + "." + "errors" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("deletePaymentInstrumentFailedDependency" + "." + "errors" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (o *DeletePaymentInstrumentFailedDependencyBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *DeletePaymentInstrumentFailedDependencyBody) UnmarshalBinary(b []byte) error {
	var res DeletePaymentInstrumentFailedDependencyBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}

/*
DeletePaymentInstrumentFailedDependencyBodyErrorsItems0 delete payment instrument failed dependency body errors items0
swagger:model DeletePaymentInstrumentFailedDependencyBodyErrorsItems0
*/
type DeletePaymentInstrumentFailedDependencyBodyErrorsItems0 struct {

	// The detailed message related to the type.
	// Read Only: true
	Message string `json:"message,omitempty"`

	// The type of error.
	//
	// Possible Values:
	//   - notFound
	//
	// Read Only: true
	Type string `json:"type,omitempty"`
}

// Validate validates this delete payment instrument failed dependency body errors items0
func (o *DeletePaymentInstrumentFailedDependencyBodyErrorsItems0) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validate this delete payment instrument failed dependency body errors items0 based on the context it is used
func (o *DeletePaymentInstrumentFailedDependencyBodyErrorsItems0) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := o.contextValidateMessage(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := o.contextValidateType(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *DeletePaymentInstrumentFailedDependencyBodyErrorsItems0) contextValidateMessage(ctx context.Context, formats strfmt.Registry) error {

	if err := validate.ReadOnly(ctx, "message", "body", string(o.Message)); err != nil {
		return err
	}

	return nil
}

func (o *DeletePaymentInstrumentFailedDependencyBodyErrorsItems0) contextValidateType(ctx context.Context, formats strfmt.Registry) error {

	if err := validate.ReadOnly(ctx, "type", "body", string(o.Type)); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (o *DeletePaymentInstrumentFailedDependencyBodyErrorsItems0) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *DeletePaymentInstrumentFailedDependencyBodyErrorsItems0) UnmarshalBinary(b []byte) error {
	var res DeletePaymentInstrumentFailedDependencyBodyErrorsItems0
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}

/*
DeletePaymentInstrumentForbiddenBody delete payment instrument forbidden body
swagger:model DeletePaymentInstrumentForbiddenBody
*/
type DeletePaymentInstrumentForbiddenBody struct {

	// errors
	// Read Only: true
	Errors []*DeletePaymentInstrumentForbiddenBodyErrorsItems0 `json:"errors"`
}

// Validate validates this delete payment instrument forbidden body
func (o *DeletePaymentInstrumentForbiddenBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateErrors(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *DeletePaymentInstrumentForbiddenBody) validateErrors(formats strfmt.Registry) error {
	if swag.IsZero(o.Errors) { // not required
		return nil
	}

	for i := 0; i < len(o.Errors); i++ {
		if swag.IsZero(o.Errors[i]) { // not required
			continue
		}

		if o.Errors[i] != nil {
			if err := o.Errors[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("deletePaymentInstrumentForbidden" + "." + "errors" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("deletePaymentInstrumentForbidden" + "." + "errors" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// ContextValidate validate this delete payment instrument forbidden body based on the context it is used
func (o *DeletePaymentInstrumentForbiddenBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := o.contextValidateErrors(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *DeletePaymentInstrumentForbiddenBody) contextValidateErrors(ctx context.Context, formats strfmt.Registry) error {

	if err := validate.ReadOnly(ctx, "deletePaymentInstrumentForbidden"+"."+"errors", "body", []*DeletePaymentInstrumentForbiddenBodyErrorsItems0(o.Errors)); err != nil {
		return err
	}

	for i := 0; i < len(o.Errors); i++ {

		if o.Errors[i] != nil {

			if swag.IsZero(o.Errors[i]) { // not required
				return nil
			}

			if err := o.Errors[i].ContextValidate(ctx, formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("deletePaymentInstrumentForbidden" + "." + "errors" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("deletePaymentInstrumentForbidden" + "." + "errors" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (o *DeletePaymentInstrumentForbiddenBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *DeletePaymentInstrumentForbiddenBody) UnmarshalBinary(b []byte) error {
	var res DeletePaymentInstrumentForbiddenBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}

/*
DeletePaymentInstrumentForbiddenBodyErrorsItems0 delete payment instrument forbidden body errors items0
swagger:model DeletePaymentInstrumentForbiddenBodyErrorsItems0
*/
type DeletePaymentInstrumentForbiddenBodyErrorsItems0 struct {

	// The detailed message related to the type.
	// Read Only: true
	Message string `json:"message,omitempty"`

	// The type of error.
	//
	// Possible Values:
	//   - forbidden
	//
	// Read Only: true
	Type string `json:"type,omitempty"`
}

// Validate validates this delete payment instrument forbidden body errors items0
func (o *DeletePaymentInstrumentForbiddenBodyErrorsItems0) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validate this delete payment instrument forbidden body errors items0 based on the context it is used
func (o *DeletePaymentInstrumentForbiddenBodyErrorsItems0) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := o.contextValidateMessage(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := o.contextValidateType(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *DeletePaymentInstrumentForbiddenBodyErrorsItems0) contextValidateMessage(ctx context.Context, formats strfmt.Registry) error {

	if err := validate.ReadOnly(ctx, "message", "body", string(o.Message)); err != nil {
		return err
	}

	return nil
}

func (o *DeletePaymentInstrumentForbiddenBodyErrorsItems0) contextValidateType(ctx context.Context, formats strfmt.Registry) error {

	if err := validate.ReadOnly(ctx, "type", "body", string(o.Type)); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (o *DeletePaymentInstrumentForbiddenBodyErrorsItems0) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *DeletePaymentInstrumentForbiddenBodyErrorsItems0) UnmarshalBinary(b []byte) error {
	var res DeletePaymentInstrumentForbiddenBodyErrorsItems0
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}

/*
DeletePaymentInstrumentGoneBody delete payment instrument gone body
swagger:model DeletePaymentInstrumentGoneBody
*/
type DeletePaymentInstrumentGoneBody struct {

	// errors
	// Read Only: true
	Errors []*DeletePaymentInstrumentGoneBodyErrorsItems0 `json:"errors"`
}

// Validate validates this delete payment instrument gone body
func (o *DeletePaymentInstrumentGoneBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateErrors(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *DeletePaymentInstrumentGoneBody) validateErrors(formats strfmt.Registry) error {
	if swag.IsZero(o.Errors) { // not required
		return nil
	}

	for i := 0; i < len(o.Errors); i++ {
		if swag.IsZero(o.Errors[i]) { // not required
			continue
		}

		if o.Errors[i] != nil {
			if err := o.Errors[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("deletePaymentInstrumentGone" + "." + "errors" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("deletePaymentInstrumentGone" + "." + "errors" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// ContextValidate validate this delete payment instrument gone body based on the context it is used
func (o *DeletePaymentInstrumentGoneBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := o.contextValidateErrors(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *DeletePaymentInstrumentGoneBody) contextValidateErrors(ctx context.Context, formats strfmt.Registry) error {

	if err := validate.ReadOnly(ctx, "deletePaymentInstrumentGone"+"."+"errors", "body", []*DeletePaymentInstrumentGoneBodyErrorsItems0(o.Errors)); err != nil {
		return err
	}

	for i := 0; i < len(o.Errors); i++ {

		if o.Errors[i] != nil {

			if swag.IsZero(o.Errors[i]) { // not required
				return nil
			}

			if err := o.Errors[i].ContextValidate(ctx, formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("deletePaymentInstrumentGone" + "." + "errors" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("deletePaymentInstrumentGone" + "." + "errors" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (o *DeletePaymentInstrumentGoneBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *DeletePaymentInstrumentGoneBody) UnmarshalBinary(b []byte) error {
	var res DeletePaymentInstrumentGoneBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}

/*
DeletePaymentInstrumentGoneBodyErrorsItems0 delete payment instrument gone body errors items0
swagger:model DeletePaymentInstrumentGoneBodyErrorsItems0
*/
type DeletePaymentInstrumentGoneBodyErrorsItems0 struct {

	// The detailed message related to the type.
	// Read Only: true
	Message string `json:"message,omitempty"`

	// The type of error.
	//
	// Possible Values:
	//   - notAvailable
	//
	// Read Only: true
	Type string `json:"type,omitempty"`
}

// Validate validates this delete payment instrument gone body errors items0
func (o *DeletePaymentInstrumentGoneBodyErrorsItems0) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validate this delete payment instrument gone body errors items0 based on the context it is used
func (o *DeletePaymentInstrumentGoneBodyErrorsItems0) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := o.contextValidateMessage(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := o.contextValidateType(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *DeletePaymentInstrumentGoneBodyErrorsItems0) contextValidateMessage(ctx context.Context, formats strfmt.Registry) error {

	if err := validate.ReadOnly(ctx, "message", "body", string(o.Message)); err != nil {
		return err
	}

	return nil
}

func (o *DeletePaymentInstrumentGoneBodyErrorsItems0) contextValidateType(ctx context.Context, formats strfmt.Registry) error {

	if err := validate.ReadOnly(ctx, "type", "body", string(o.Type)); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (o *DeletePaymentInstrumentGoneBodyErrorsItems0) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *DeletePaymentInstrumentGoneBodyErrorsItems0) UnmarshalBinary(b []byte) error {
	var res DeletePaymentInstrumentGoneBodyErrorsItems0
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}

/*
DeletePaymentInstrumentInternalServerErrorBody delete payment instrument internal server error body
swagger:model DeletePaymentInstrumentInternalServerErrorBody
*/
type DeletePaymentInstrumentInternalServerErrorBody struct {

	// errors
	// Read Only: true
	Errors []*DeletePaymentInstrumentInternalServerErrorBodyErrorsItems0 `json:"errors"`
}

// Validate validates this delete payment instrument internal server error body
func (o *DeletePaymentInstrumentInternalServerErrorBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateErrors(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *DeletePaymentInstrumentInternalServerErrorBody) validateErrors(formats strfmt.Registry) error {
	if swag.IsZero(o.Errors) { // not required
		return nil
	}

	for i := 0; i < len(o.Errors); i++ {
		if swag.IsZero(o.Errors[i]) { // not required
			continue
		}

		if o.Errors[i] != nil {
			if err := o.Errors[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("deletePaymentInstrumentInternalServerError" + "." + "errors" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("deletePaymentInstrumentInternalServerError" + "." + "errors" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// ContextValidate validate this delete payment instrument internal server error body based on the context it is used
func (o *DeletePaymentInstrumentInternalServerErrorBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := o.contextValidateErrors(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *DeletePaymentInstrumentInternalServerErrorBody) contextValidateErrors(ctx context.Context, formats strfmt.Registry) error {

	if err := validate.ReadOnly(ctx, "deletePaymentInstrumentInternalServerError"+"."+"errors", "body", []*DeletePaymentInstrumentInternalServerErrorBodyErrorsItems0(o.Errors)); err != nil {
		return err
	}

	for i := 0; i < len(o.Errors); i++ {

		if o.Errors[i] != nil {

			if swag.IsZero(o.Errors[i]) { // not required
				return nil
			}

			if err := o.Errors[i].ContextValidate(ctx, formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("deletePaymentInstrumentInternalServerError" + "." + "errors" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("deletePaymentInstrumentInternalServerError" + "." + "errors" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (o *DeletePaymentInstrumentInternalServerErrorBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *DeletePaymentInstrumentInternalServerErrorBody) UnmarshalBinary(b []byte) error {
	var res DeletePaymentInstrumentInternalServerErrorBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}

/*
DeletePaymentInstrumentInternalServerErrorBodyErrorsItems0 delete payment instrument internal server error body errors items0
swagger:model DeletePaymentInstrumentInternalServerErrorBodyErrorsItems0
*/
type DeletePaymentInstrumentInternalServerErrorBodyErrorsItems0 struct {

	// The detailed message related to the type.
	// Read Only: true
	Message string `json:"message,omitempty"`

	// The type of error.
	//
	// Possible Values:
	//   - internalError
	//
	// Read Only: true
	Type string `json:"type,omitempty"`
}

// Validate validates this delete payment instrument internal server error body errors items0
func (o *DeletePaymentInstrumentInternalServerErrorBodyErrorsItems0) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validate this delete payment instrument internal server error body errors items0 based on the context it is used
func (o *DeletePaymentInstrumentInternalServerErrorBodyErrorsItems0) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := o.contextValidateMessage(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := o.contextValidateType(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *DeletePaymentInstrumentInternalServerErrorBodyErrorsItems0) contextValidateMessage(ctx context.Context, formats strfmt.Registry) error {

	if err := validate.ReadOnly(ctx, "message", "body", string(o.Message)); err != nil {
		return err
	}

	return nil
}

func (o *DeletePaymentInstrumentInternalServerErrorBodyErrorsItems0) contextValidateType(ctx context.Context, formats strfmt.Registry) error {

	if err := validate.ReadOnly(ctx, "type", "body", string(o.Type)); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (o *DeletePaymentInstrumentInternalServerErrorBodyErrorsItems0) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *DeletePaymentInstrumentInternalServerErrorBodyErrorsItems0) UnmarshalBinary(b []byte) error {
	var res DeletePaymentInstrumentInternalServerErrorBodyErrorsItems0
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}

/*
DeletePaymentInstrumentNotFoundBody delete payment instrument not found body
swagger:model DeletePaymentInstrumentNotFoundBody
*/
type DeletePaymentInstrumentNotFoundBody struct {

	// errors
	// Read Only: true
	Errors []*DeletePaymentInstrumentNotFoundBodyErrorsItems0 `json:"errors"`
}

// Validate validates this delete payment instrument not found body
func (o *DeletePaymentInstrumentNotFoundBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateErrors(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *DeletePaymentInstrumentNotFoundBody) validateErrors(formats strfmt.Registry) error {
	if swag.IsZero(o.Errors) { // not required
		return nil
	}

	for i := 0; i < len(o.Errors); i++ {
		if swag.IsZero(o.Errors[i]) { // not required
			continue
		}

		if o.Errors[i] != nil {
			if err := o.Errors[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("deletePaymentInstrumentNotFound" + "." + "errors" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("deletePaymentInstrumentNotFound" + "." + "errors" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// ContextValidate validate this delete payment instrument not found body based on the context it is used
func (o *DeletePaymentInstrumentNotFoundBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := o.contextValidateErrors(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *DeletePaymentInstrumentNotFoundBody) contextValidateErrors(ctx context.Context, formats strfmt.Registry) error {

	if err := validate.ReadOnly(ctx, "deletePaymentInstrumentNotFound"+"."+"errors", "body", []*DeletePaymentInstrumentNotFoundBodyErrorsItems0(o.Errors)); err != nil {
		return err
	}

	for i := 0; i < len(o.Errors); i++ {

		if o.Errors[i] != nil {

			if swag.IsZero(o.Errors[i]) { // not required
				return nil
			}

			if err := o.Errors[i].ContextValidate(ctx, formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("deletePaymentInstrumentNotFound" + "." + "errors" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("deletePaymentInstrumentNotFound" + "." + "errors" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (o *DeletePaymentInstrumentNotFoundBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *DeletePaymentInstrumentNotFoundBody) UnmarshalBinary(b []byte) error {
	var res DeletePaymentInstrumentNotFoundBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}

/*
DeletePaymentInstrumentNotFoundBodyErrorsItems0 delete payment instrument not found body errors items0
swagger:model DeletePaymentInstrumentNotFoundBodyErrorsItems0
*/
type DeletePaymentInstrumentNotFoundBodyErrorsItems0 struct {

	// The detailed message related to the type.
	// Read Only: true
	Message string `json:"message,omitempty"`

	// The type of error.
	//
	// Possible Values:
	//   - notFound
	//
	// Read Only: true
	Type string `json:"type,omitempty"`
}

// Validate validates this delete payment instrument not found body errors items0
func (o *DeletePaymentInstrumentNotFoundBodyErrorsItems0) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validate this delete payment instrument not found body errors items0 based on the context it is used
func (o *DeletePaymentInstrumentNotFoundBodyErrorsItems0) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := o.contextValidateMessage(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := o.contextValidateType(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *DeletePaymentInstrumentNotFoundBodyErrorsItems0) contextValidateMessage(ctx context.Context, formats strfmt.Registry) error {

	if err := validate.ReadOnly(ctx, "message", "body", string(o.Message)); err != nil {
		return err
	}

	return nil
}

func (o *DeletePaymentInstrumentNotFoundBodyErrorsItems0) contextValidateType(ctx context.Context, formats strfmt.Registry) error {

	if err := validate.ReadOnly(ctx, "type", "body", string(o.Type)); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (o *DeletePaymentInstrumentNotFoundBodyErrorsItems0) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *DeletePaymentInstrumentNotFoundBodyErrorsItems0) UnmarshalBinary(b []byte) error {
	var res DeletePaymentInstrumentNotFoundBodyErrorsItems0
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
