// Code generated by go-swagger; DO NOT EDIT.

package subscriptions

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetRecurringSubscriptionCodeParams creates a new GetRecurringSubscriptionCodeParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetRecurringSubscriptionCodeParams() *GetRecurringSubscriptionCodeParams {
	return &GetRecurringSubscriptionCodeParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetRecurringSubscriptionCodeParamsWithTimeout creates a new GetRecurringSubscriptionCodeParams object
// with the ability to set a timeout on a request.
func NewGetRecurringSubscriptionCodeParamsWithTimeout(timeout time.Duration) *GetRecurringSubscriptionCodeParams {
	return &GetRecurringSubscriptionCodeParams{
		timeout: timeout,
	}
}

// NewGetRecurringSubscriptionCodeParamsWithContext creates a new GetRecurringSubscriptionCodeParams object
// with the ability to set a context for a request.
func NewGetRecurringSubscriptionCodeParamsWithContext(ctx context.Context) *GetRecurringSubscriptionCodeParams {
	return &GetRecurringSubscriptionCodeParams{
		Context: ctx,
	}
}

// NewGetRecurringSubscriptionCodeParamsWithHTTPClient creates a new GetRecurringSubscriptionCodeParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetRecurringSubscriptionCodeParamsWithHTTPClient(client *http.Client) *GetRecurringSubscriptionCodeParams {
	return &GetRecurringSubscriptionCodeParams{
		HTTPClient: client,
	}
}

/*
GetRecurringSubscriptionCodeParams contains all the parameters to send to the API endpoint

	for the get recurring subscription code operation.

	Typically these are written to a http.Request.
*/
type GetRecurringSubscriptionCodeParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get recurring subscription code params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetRecurringSubscriptionCodeParams) WithDefaults() *GetRecurringSubscriptionCodeParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get recurring subscription code params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetRecurringSubscriptionCodeParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get recurring subscription code params
func (o *GetRecurringSubscriptionCodeParams) WithTimeout(timeout time.Duration) *GetRecurringSubscriptionCodeParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get recurring subscription code params
func (o *GetRecurringSubscriptionCodeParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get recurring subscription code params
func (o *GetRecurringSubscriptionCodeParams) WithContext(ctx context.Context) *GetRecurringSubscriptionCodeParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get recurring subscription code params
func (o *GetRecurringSubscriptionCodeParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get recurring subscription code params
func (o *GetRecurringSubscriptionCodeParams) WithHTTPClient(client *http.Client) *GetRecurringSubscriptionCodeParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get recurring subscription code params
func (o *GetRecurringSubscriptionCodeParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *GetRecurringSubscriptionCodeParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
