// Code generated by go-swagger; DO NOT EDIT.

package report_subscriptions

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"encoding/json"
	"fmt"
	"io"
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// CreateSubscriptionReportReader is a Reader for the CreateSubscriptionReport structure.
type CreateSubscriptionReportReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *CreateSubscriptionReportReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewCreateSubscriptionReportOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 304:
		result := NewCreateSubscriptionReportNotModified()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 400:
		result := NewCreateSubscriptionReportBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[PUT /reporting/v3/report-subscriptions] createSubscriptionReport", response, response.Code())
	}
}

// NewCreateSubscriptionReportOK creates a CreateSubscriptionReportOK with default headers values
func NewCreateSubscriptionReportOK() *CreateSubscriptionReportOK {
	return &CreateSubscriptionReportOK{}
}

/*
CreateSubscriptionReportOK describes a response with status code 200, with default header values.

Ok
*/
type CreateSubscriptionReportOK struct {
}

// IsSuccess returns true when this create subscription report o k response has a 2xx status code
func (o *CreateSubscriptionReportOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this create subscription report o k response has a 3xx status code
func (o *CreateSubscriptionReportOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this create subscription report o k response has a 4xx status code
func (o *CreateSubscriptionReportOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this create subscription report o k response has a 5xx status code
func (o *CreateSubscriptionReportOK) IsServerError() bool {
	return false
}

// IsCode returns true when this create subscription report o k response a status code equal to that given
func (o *CreateSubscriptionReportOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the create subscription report o k response
func (o *CreateSubscriptionReportOK) Code() int {
	return 200
}

func (o *CreateSubscriptionReportOK) Error() string {
	return fmt.Sprintf("[PUT /reporting/v3/report-subscriptions][%d] createSubscriptionReportOK", 200)
}

func (o *CreateSubscriptionReportOK) String() string {
	return fmt.Sprintf("[PUT /reporting/v3/report-subscriptions][%d] createSubscriptionReportOK", 200)
}

func (o *CreateSubscriptionReportOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewCreateSubscriptionReportNotModified creates a CreateSubscriptionReportNotModified with default headers values
func NewCreateSubscriptionReportNotModified() *CreateSubscriptionReportNotModified {
	return &CreateSubscriptionReportNotModified{}
}

/*
CreateSubscriptionReportNotModified describes a response with status code 304, with default header values.

NOT MODIFIED
*/
type CreateSubscriptionReportNotModified struct {
}

// IsSuccess returns true when this create subscription report not modified response has a 2xx status code
func (o *CreateSubscriptionReportNotModified) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this create subscription report not modified response has a 3xx status code
func (o *CreateSubscriptionReportNotModified) IsRedirect() bool {
	return true
}

// IsClientError returns true when this create subscription report not modified response has a 4xx status code
func (o *CreateSubscriptionReportNotModified) IsClientError() bool {
	return false
}

// IsServerError returns true when this create subscription report not modified response has a 5xx status code
func (o *CreateSubscriptionReportNotModified) IsServerError() bool {
	return false
}

// IsCode returns true when this create subscription report not modified response a status code equal to that given
func (o *CreateSubscriptionReportNotModified) IsCode(code int) bool {
	return code == 304
}

// Code gets the status code for the create subscription report not modified response
func (o *CreateSubscriptionReportNotModified) Code() int {
	return 304
}

func (o *CreateSubscriptionReportNotModified) Error() string {
	return fmt.Sprintf("[PUT /reporting/v3/report-subscriptions][%d] createSubscriptionReportNotModified", 304)
}

func (o *CreateSubscriptionReportNotModified) String() string {
	return fmt.Sprintf("[PUT /reporting/v3/report-subscriptions][%d] createSubscriptionReportNotModified", 304)
}

func (o *CreateSubscriptionReportNotModified) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewCreateSubscriptionReportBadRequest creates a CreateSubscriptionReportBadRequest with default headers values
func NewCreateSubscriptionReportBadRequest() *CreateSubscriptionReportBadRequest {
	return &CreateSubscriptionReportBadRequest{}
}

/*
CreateSubscriptionReportBadRequest describes a response with status code 400, with default header values.

Invalid request
*/
type CreateSubscriptionReportBadRequest struct {
	Payload *CreateSubscriptionReportBadRequestBody
}

// IsSuccess returns true when this create subscription report bad request response has a 2xx status code
func (o *CreateSubscriptionReportBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this create subscription report bad request response has a 3xx status code
func (o *CreateSubscriptionReportBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this create subscription report bad request response has a 4xx status code
func (o *CreateSubscriptionReportBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this create subscription report bad request response has a 5xx status code
func (o *CreateSubscriptionReportBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this create subscription report bad request response a status code equal to that given
func (o *CreateSubscriptionReportBadRequest) IsCode(code int) bool {
	return code == 400
}

// Code gets the status code for the create subscription report bad request response
func (o *CreateSubscriptionReportBadRequest) Code() int {
	return 400
}

func (o *CreateSubscriptionReportBadRequest) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PUT /reporting/v3/report-subscriptions][%d] createSubscriptionReportBadRequest %s", 400, payload)
}

func (o *CreateSubscriptionReportBadRequest) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PUT /reporting/v3/report-subscriptions][%d] createSubscriptionReportBadRequest %s", 400, payload)
}

func (o *CreateSubscriptionReportBadRequest) GetPayload() *CreateSubscriptionReportBadRequestBody {
	return o.Payload
}

func (o *CreateSubscriptionReportBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(CreateSubscriptionReportBadRequestBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

/*
CreateSubscriptionReportBadRequestBody Error Bean
swagger:model CreateSubscriptionReportBadRequestBody
*/
type CreateSubscriptionReportBadRequestBody struct {

	// Error code
	// Required: true
	Code *string `json:"code"`

	// Correlation Id
	CorrelationID string `json:"correlationId,omitempty"`

	// Error Detail
	Detail string `json:"detail,omitempty"`

	// Error fields List
	Fields []*CreateSubscriptionReportBadRequestBodyFieldsItems0 `json:"fields"`

	// Localization Key Name
	LocalizationKey string `json:"localizationKey,omitempty"`

	// Error message
	// Required: true
	Message *string `json:"message"`
}

// Validate validates this create subscription report bad request body
func (o *CreateSubscriptionReportBadRequestBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateCode(formats); err != nil {
		res = append(res, err)
	}

	if err := o.validateFields(formats); err != nil {
		res = append(res, err)
	}

	if err := o.validateMessage(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *CreateSubscriptionReportBadRequestBody) validateCode(formats strfmt.Registry) error {

	if err := validate.Required("createSubscriptionReportBadRequest"+"."+"code", "body", o.Code); err != nil {
		return err
	}

	return nil
}

func (o *CreateSubscriptionReportBadRequestBody) validateFields(formats strfmt.Registry) error {
	if swag.IsZero(o.Fields) { // not required
		return nil
	}

	for i := 0; i < len(o.Fields); i++ {
		if swag.IsZero(o.Fields[i]) { // not required
			continue
		}

		if o.Fields[i] != nil {
			if err := o.Fields[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("createSubscriptionReportBadRequest" + "." + "fields" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("createSubscriptionReportBadRequest" + "." + "fields" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

func (o *CreateSubscriptionReportBadRequestBody) validateMessage(formats strfmt.Registry) error {

	if err := validate.Required("createSubscriptionReportBadRequest"+"."+"message", "body", o.Message); err != nil {
		return err
	}

	return nil
}

// ContextValidate validate this create subscription report bad request body based on the context it is used
func (o *CreateSubscriptionReportBadRequestBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := o.contextValidateFields(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *CreateSubscriptionReportBadRequestBody) contextValidateFields(ctx context.Context, formats strfmt.Registry) error {

	for i := 0; i < len(o.Fields); i++ {

		if o.Fields[i] != nil {

			if swag.IsZero(o.Fields[i]) { // not required
				return nil
			}

			if err := o.Fields[i].ContextValidate(ctx, formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("createSubscriptionReportBadRequest" + "." + "fields" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("createSubscriptionReportBadRequest" + "." + "fields" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (o *CreateSubscriptionReportBadRequestBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *CreateSubscriptionReportBadRequestBody) UnmarshalBinary(b []byte) error {
	var res CreateSubscriptionReportBadRequestBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}

/*
CreateSubscriptionReportBadRequestBodyFieldsItems0 Provide validation failed input field details
swagger:model CreateSubscriptionReportBadRequestBodyFieldsItems0
*/
type CreateSubscriptionReportBadRequestBodyFieldsItems0 struct {

	// Localized Key Name
	LocalizationKey string `json:"localizationKey,omitempty"`

	// Error description about validation failed field
	Message string `json:"message,omitempty"`

	// Path of the failed property
	Path string `json:"path,omitempty"`
}

// Validate validates this create subscription report bad request body fields items0
func (o *CreateSubscriptionReportBadRequestBodyFieldsItems0) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this create subscription report bad request body fields items0 based on context it is used
func (o *CreateSubscriptionReportBadRequestBodyFieldsItems0) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *CreateSubscriptionReportBadRequestBodyFieldsItems0) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *CreateSubscriptionReportBadRequestBodyFieldsItems0) UnmarshalBinary(b []byte) error {
	var res CreateSubscriptionReportBadRequestBodyFieldsItems0
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}

/*
CreateSubscriptionReportBody create subscription report body
swagger:model CreateSubscriptionReportBody
*/
type CreateSubscriptionReportBody struct {

	// Valid GroupName
	// Example: CEMEA Group
	// Pattern: [a-zA-Z0-9-_ ]+
	GroupName string `json:"groupName,omitempty"`

	// Valid CyberSource organizationId
	// Example: Merchant 1
	// Pattern: [a-zA-Z0-9-_]+
	OrganizationID string `json:"organizationId,omitempty"`

	// Valid Report Definition Name
	// Example: TransactionDetailReportClass
	// Required: true
	// Max Length: 80
	// Min Length: 1
	// Pattern: [a-zA-Z0-9-]+
	ReportDefinitionName *string `json:"reportDefinitionName"`

	// report fields
	// Example: ["Request.RequestID","Request.TransactionDate","Request.MerchantID"]
	// Required: true
	ReportFields []string `json:"reportFields"`

	// List of filters to apply
	// Example: {"Application.Name":["ics_auth","ics_bill"]}
	ReportFilters map[string][]string `json:"reportFilters,omitempty"`

	// 'The frequency for which subscription is created.'
	// **NOTE: Do not document USER_DEFINED Frequency field in developer center**
	// Valid Values:
	//   - 'DAILY'
	//   - 'WEEKLY'
	//   - 'MONTHLY'
	//   - 'USER_DEFINED'
	//
	// Example: DAILY
	// Required: true
	ReportFrequency *string `json:"reportFrequency"`

	// If the reportFrequency is User-defined, reportInterval should be in **ISO 8601 time format**
	// Please refer the following link to know more about ISO 8601 format.[Rfc Time Format](https://en.wikipedia.org/wiki/ISO_8601#Durations)
	//
	// **Example time format for 2 hours and 30 Mins:**
	//   - PT2H30M
	// **NOTE: Do not document reportInterval field in developer center**
	//
	// Pattern: ^PT((([1-9]|1[0-9]|2[0-3])H(([1-9]|[1-4][0-9]|5[0-9])M)?)|((([1-9]|1[0-9]|2[0-3])H)?([1-9]|[1-4][0-9]|5[0-9])M))$
	ReportInterval string `json:"reportInterval,omitempty"`

	// Valid values:
	// - application/xml
	// - text/csv
	//
	// Example: application/xml
	// Required: true
	ReportMimeType *string `json:"reportMimeType"`

	// report name
	// Example: My Daily Subscription
	// Required: true
	// Max Length: 128
	// Min Length: 1
	// Pattern: [a-zA-Z0-9-_ ]+
	ReportName *string `json:"reportName"`

	// report preferences
	ReportPreferences *CreateSubscriptionReportParamsBodyReportPreferences `json:"reportPreferences,omitempty"`

	// This is the start day if the frequency is WEEKLY or MONTHLY. The value varies from 1-7 for WEEKLY and 1-31 for MONTHLY. For WEEKLY 1 means Sunday and 7 means Saturday. By default the value is 1.
	// Maximum: 31
	// Minimum: 1
	StartDay int64 `json:"startDay,omitempty"`

	// The hour at which the report generation should start. It should be in hhmm format.
	// Example: 0900
	// Required: true
	StartTime *string `json:"startTime"`

	// timezone
	// Example: America/Chicago
	// Required: true
	Timezone *string `json:"timezone"`
}

// Validate validates this create subscription report body
func (o *CreateSubscriptionReportBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateGroupName(formats); err != nil {
		res = append(res, err)
	}

	if err := o.validateOrganizationID(formats); err != nil {
		res = append(res, err)
	}

	if err := o.validateReportDefinitionName(formats); err != nil {
		res = append(res, err)
	}

	if err := o.validateReportFields(formats); err != nil {
		res = append(res, err)
	}

	if err := o.validateReportFrequency(formats); err != nil {
		res = append(res, err)
	}

	if err := o.validateReportInterval(formats); err != nil {
		res = append(res, err)
	}

	if err := o.validateReportMimeType(formats); err != nil {
		res = append(res, err)
	}

	if err := o.validateReportName(formats); err != nil {
		res = append(res, err)
	}

	if err := o.validateReportPreferences(formats); err != nil {
		res = append(res, err)
	}

	if err := o.validateStartDay(formats); err != nil {
		res = append(res, err)
	}

	if err := o.validateStartTime(formats); err != nil {
		res = append(res, err)
	}

	if err := o.validateTimezone(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *CreateSubscriptionReportBody) validateGroupName(formats strfmt.Registry) error {
	if swag.IsZero(o.GroupName) { // not required
		return nil
	}

	if err := validate.Pattern("createReportSubscriptionRequest"+"."+"groupName", "body", o.GroupName, `[a-zA-Z0-9-_ ]+`); err != nil {
		return err
	}

	return nil
}

func (o *CreateSubscriptionReportBody) validateOrganizationID(formats strfmt.Registry) error {
	if swag.IsZero(o.OrganizationID) { // not required
		return nil
	}

	if err := validate.Pattern("createReportSubscriptionRequest"+"."+"organizationId", "body", o.OrganizationID, `[a-zA-Z0-9-_]+`); err != nil {
		return err
	}

	return nil
}

func (o *CreateSubscriptionReportBody) validateReportDefinitionName(formats strfmt.Registry) error {

	if err := validate.Required("createReportSubscriptionRequest"+"."+"reportDefinitionName", "body", o.ReportDefinitionName); err != nil {
		return err
	}

	if err := validate.MinLength("createReportSubscriptionRequest"+"."+"reportDefinitionName", "body", *o.ReportDefinitionName, 1); err != nil {
		return err
	}

	if err := validate.MaxLength("createReportSubscriptionRequest"+"."+"reportDefinitionName", "body", *o.ReportDefinitionName, 80); err != nil {
		return err
	}

	if err := validate.Pattern("createReportSubscriptionRequest"+"."+"reportDefinitionName", "body", *o.ReportDefinitionName, `[a-zA-Z0-9-]+`); err != nil {
		return err
	}

	return nil
}

func (o *CreateSubscriptionReportBody) validateReportFields(formats strfmt.Registry) error {

	if err := validate.Required("createReportSubscriptionRequest"+"."+"reportFields", "body", o.ReportFields); err != nil {
		return err
	}

	return nil
}

func (o *CreateSubscriptionReportBody) validateReportFrequency(formats strfmt.Registry) error {

	if err := validate.Required("createReportSubscriptionRequest"+"."+"reportFrequency", "body", o.ReportFrequency); err != nil {
		return err
	}

	return nil
}

func (o *CreateSubscriptionReportBody) validateReportInterval(formats strfmt.Registry) error {
	if swag.IsZero(o.ReportInterval) { // not required
		return nil
	}

	if err := validate.Pattern("createReportSubscriptionRequest"+"."+"reportInterval", "body", o.ReportInterval, `^PT((([1-9]|1[0-9]|2[0-3])H(([1-9]|[1-4][0-9]|5[0-9])M)?)|((([1-9]|1[0-9]|2[0-3])H)?([1-9]|[1-4][0-9]|5[0-9])M))$`); err != nil {
		return err
	}

	return nil
}

func (o *CreateSubscriptionReportBody) validateReportMimeType(formats strfmt.Registry) error {

	if err := validate.Required("createReportSubscriptionRequest"+"."+"reportMimeType", "body", o.ReportMimeType); err != nil {
		return err
	}

	return nil
}

func (o *CreateSubscriptionReportBody) validateReportName(formats strfmt.Registry) error {

	if err := validate.Required("createReportSubscriptionRequest"+"."+"reportName", "body", o.ReportName); err != nil {
		return err
	}

	if err := validate.MinLength("createReportSubscriptionRequest"+"."+"reportName", "body", *o.ReportName, 1); err != nil {
		return err
	}

	if err := validate.MaxLength("createReportSubscriptionRequest"+"."+"reportName", "body", *o.ReportName, 128); err != nil {
		return err
	}

	if err := validate.Pattern("createReportSubscriptionRequest"+"."+"reportName", "body", *o.ReportName, `[a-zA-Z0-9-_ ]+`); err != nil {
		return err
	}

	return nil
}

func (o *CreateSubscriptionReportBody) validateReportPreferences(formats strfmt.Registry) error {
	if swag.IsZero(o.ReportPreferences) { // not required
		return nil
	}

	if o.ReportPreferences != nil {
		if err := o.ReportPreferences.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("createReportSubscriptionRequest" + "." + "reportPreferences")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("createReportSubscriptionRequest" + "." + "reportPreferences")
			}
			return err
		}
	}

	return nil
}

func (o *CreateSubscriptionReportBody) validateStartDay(formats strfmt.Registry) error {
	if swag.IsZero(o.StartDay) { // not required
		return nil
	}

	if err := validate.MinimumInt("createReportSubscriptionRequest"+"."+"startDay", "body", o.StartDay, 1, false); err != nil {
		return err
	}

	if err := validate.MaximumInt("createReportSubscriptionRequest"+"."+"startDay", "body", o.StartDay, 31, false); err != nil {
		return err
	}

	return nil
}

func (o *CreateSubscriptionReportBody) validateStartTime(formats strfmt.Registry) error {

	if err := validate.Required("createReportSubscriptionRequest"+"."+"startTime", "body", o.StartTime); err != nil {
		return err
	}

	return nil
}

func (o *CreateSubscriptionReportBody) validateTimezone(formats strfmt.Registry) error {

	if err := validate.Required("createReportSubscriptionRequest"+"."+"timezone", "body", o.Timezone); err != nil {
		return err
	}

	return nil
}

// ContextValidate validate this create subscription report body based on the context it is used
func (o *CreateSubscriptionReportBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := o.contextValidateReportPreferences(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *CreateSubscriptionReportBody) contextValidateReportPreferences(ctx context.Context, formats strfmt.Registry) error {

	if o.ReportPreferences != nil {

		if swag.IsZero(o.ReportPreferences) { // not required
			return nil
		}

		if err := o.ReportPreferences.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("createReportSubscriptionRequest" + "." + "reportPreferences")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("createReportSubscriptionRequest" + "." + "reportPreferences")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (o *CreateSubscriptionReportBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *CreateSubscriptionReportBody) UnmarshalBinary(b []byte) error {
	var res CreateSubscriptionReportBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}

/*
CreateSubscriptionReportParamsBodyReportPreferences Report Preferences
swagger:model CreateSubscriptionReportParamsBodyReportPreferences
*/
type CreateSubscriptionReportParamsBodyReportPreferences struct {

	// Specify the field naming convention to be followed in reports (applicable to only csv report formats)
	//
	// Valid values:
	// - SOAPI
	// - SCMP
	//
	FieldNameConvention string `json:"fieldNameConvention,omitempty"`

	// Indicator to determine whether negative sign infront of amount for all refunded transaction
	SignedAmounts bool `json:"signedAmounts,omitempty"`
}

// Validate validates this create subscription report params body report preferences
func (o *CreateSubscriptionReportParamsBodyReportPreferences) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this create subscription report params body report preferences based on context it is used
func (o *CreateSubscriptionReportParamsBodyReportPreferences) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *CreateSubscriptionReportParamsBodyReportPreferences) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *CreateSubscriptionReportParamsBodyReportPreferences) UnmarshalBinary(b []byte) error {
	var res CreateSubscriptionReportParamsBodyReportPreferences
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
