// Code generated by go-swagger; DO NOT EDIT.

package create_new_webhooks

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewFindProductsToSubscribeParams creates a new FindProductsToSubscribeParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewFindProductsToSubscribeParams() *FindProductsToSubscribeParams {
	return &FindProductsToSubscribeParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewFindProductsToSubscribeParamsWithTimeout creates a new FindProductsToSubscribeParams object
// with the ability to set a timeout on a request.
func NewFindProductsToSubscribeParamsWithTimeout(timeout time.Duration) *FindProductsToSubscribeParams {
	return &FindProductsToSubscribeParams{
		timeout: timeout,
	}
}

// NewFindProductsToSubscribeParamsWithContext creates a new FindProductsToSubscribeParams object
// with the ability to set a context for a request.
func NewFindProductsToSubscribeParamsWithContext(ctx context.Context) *FindProductsToSubscribeParams {
	return &FindProductsToSubscribeParams{
		Context: ctx,
	}
}

// NewFindProductsToSubscribeParamsWithHTTPClient creates a new FindProductsToSubscribeParams object
// with the ability to set a custom HTTPClient for a request.
func NewFindProductsToSubscribeParamsWithHTTPClient(client *http.Client) *FindProductsToSubscribeParams {
	return &FindProductsToSubscribeParams{
		HTTPClient: client,
	}
}

/*
FindProductsToSubscribeParams contains all the parameters to send to the API endpoint

	for the find products to subscribe operation.

	Typically these are written to a http.Request.
*/
type FindProductsToSubscribeParams struct {

	/* OrganizationID.

	   The Organization Identifier.
	*/
	OrganizationID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the find products to subscribe params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *FindProductsToSubscribeParams) WithDefaults() *FindProductsToSubscribeParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the find products to subscribe params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *FindProductsToSubscribeParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the find products to subscribe params
func (o *FindProductsToSubscribeParams) WithTimeout(timeout time.Duration) *FindProductsToSubscribeParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the find products to subscribe params
func (o *FindProductsToSubscribeParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the find products to subscribe params
func (o *FindProductsToSubscribeParams) WithContext(ctx context.Context) *FindProductsToSubscribeParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the find products to subscribe params
func (o *FindProductsToSubscribeParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the find products to subscribe params
func (o *FindProductsToSubscribeParams) WithHTTPClient(client *http.Client) *FindProductsToSubscribeParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the find products to subscribe params
func (o *FindProductsToSubscribeParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithOrganizationID adds the organizationID to the find products to subscribe params
func (o *FindProductsToSubscribeParams) WithOrganizationID(organizationID string) *FindProductsToSubscribeParams {
	o.SetOrganizationID(organizationID)
	return o
}

// SetOrganizationID adds the organizationId to the find products to subscribe params
func (o *FindProductsToSubscribeParams) SetOrganizationID(organizationID string) {
	o.OrganizationID = organizationID
}

// WriteToRequest writes these params to a swagger request
func (o *FindProductsToSubscribeParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param organizationId
	if err := r.SetPathParam("organizationId", o.OrganizationID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
