// Code generated by go-swagger; DO NOT EDIT.

package unified_checkout_capture_context

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGenerateUnifiedCheckoutCaptureContextParams creates a new GenerateUnifiedCheckoutCaptureContextParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGenerateUnifiedCheckoutCaptureContextParams() *GenerateUnifiedCheckoutCaptureContextParams {
	return &GenerateUnifiedCheckoutCaptureContextParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGenerateUnifiedCheckoutCaptureContextParamsWithTimeout creates a new GenerateUnifiedCheckoutCaptureContextParams object
// with the ability to set a timeout on a request.
func NewGenerateUnifiedCheckoutCaptureContextParamsWithTimeout(timeout time.Duration) *GenerateUnifiedCheckoutCaptureContextParams {
	return &GenerateUnifiedCheckoutCaptureContextParams{
		timeout: timeout,
	}
}

// NewGenerateUnifiedCheckoutCaptureContextParamsWithContext creates a new GenerateUnifiedCheckoutCaptureContextParams object
// with the ability to set a context for a request.
func NewGenerateUnifiedCheckoutCaptureContextParamsWithContext(ctx context.Context) *GenerateUnifiedCheckoutCaptureContextParams {
	return &GenerateUnifiedCheckoutCaptureContextParams{
		Context: ctx,
	}
}

// NewGenerateUnifiedCheckoutCaptureContextParamsWithHTTPClient creates a new GenerateUnifiedCheckoutCaptureContextParams object
// with the ability to set a custom HTTPClient for a request.
func NewGenerateUnifiedCheckoutCaptureContextParamsWithHTTPClient(client *http.Client) *GenerateUnifiedCheckoutCaptureContextParams {
	return &GenerateUnifiedCheckoutCaptureContextParams{
		HTTPClient: client,
	}
}

/*
GenerateUnifiedCheckoutCaptureContextParams contains all the parameters to send to the API endpoint

	for the generate unified checkout capture context operation.

	Typically these are written to a http.Request.
*/
type GenerateUnifiedCheckoutCaptureContextParams struct {

	// GenerateUnifiedCheckoutCaptureContextRequest.
	GenerateUnifiedCheckoutCaptureContextRequest GenerateUnifiedCheckoutCaptureContextBody

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the generate unified checkout capture context params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GenerateUnifiedCheckoutCaptureContextParams) WithDefaults() *GenerateUnifiedCheckoutCaptureContextParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the generate unified checkout capture context params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GenerateUnifiedCheckoutCaptureContextParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the generate unified checkout capture context params
func (o *GenerateUnifiedCheckoutCaptureContextParams) WithTimeout(timeout time.Duration) *GenerateUnifiedCheckoutCaptureContextParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the generate unified checkout capture context params
func (o *GenerateUnifiedCheckoutCaptureContextParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the generate unified checkout capture context params
func (o *GenerateUnifiedCheckoutCaptureContextParams) WithContext(ctx context.Context) *GenerateUnifiedCheckoutCaptureContextParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the generate unified checkout capture context params
func (o *GenerateUnifiedCheckoutCaptureContextParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the generate unified checkout capture context params
func (o *GenerateUnifiedCheckoutCaptureContextParams) WithHTTPClient(client *http.Client) *GenerateUnifiedCheckoutCaptureContextParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the generate unified checkout capture context params
func (o *GenerateUnifiedCheckoutCaptureContextParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithGenerateUnifiedCheckoutCaptureContextRequest adds the generateUnifiedCheckoutCaptureContextRequest to the generate unified checkout capture context params
func (o *GenerateUnifiedCheckoutCaptureContextParams) WithGenerateUnifiedCheckoutCaptureContextRequest(generateUnifiedCheckoutCaptureContextRequest GenerateUnifiedCheckoutCaptureContextBody) *GenerateUnifiedCheckoutCaptureContextParams {
	o.SetGenerateUnifiedCheckoutCaptureContextRequest(generateUnifiedCheckoutCaptureContextRequest)
	return o
}

// SetGenerateUnifiedCheckoutCaptureContextRequest adds the generateUnifiedCheckoutCaptureContextRequest to the generate unified checkout capture context params
func (o *GenerateUnifiedCheckoutCaptureContextParams) SetGenerateUnifiedCheckoutCaptureContextRequest(generateUnifiedCheckoutCaptureContextRequest GenerateUnifiedCheckoutCaptureContextBody) {
	o.GenerateUnifiedCheckoutCaptureContextRequest = generateUnifiedCheckoutCaptureContextRequest
}

// WriteToRequest writes these params to a swagger request
func (o *GenerateUnifiedCheckoutCaptureContextParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if err := r.SetBodyParam(o.GenerateUnifiedCheckoutCaptureContextRequest); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
