// Code generated by go-swagger; DO NOT EDIT.

package billing_agreements

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewBillingAgreementsRegistrationParams creates a new BillingAgreementsRegistrationParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewBillingAgreementsRegistrationParams() *BillingAgreementsRegistrationParams {
	return &BillingAgreementsRegistrationParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewBillingAgreementsRegistrationParamsWithTimeout creates a new BillingAgreementsRegistrationParams object
// with the ability to set a timeout on a request.
func NewBillingAgreementsRegistrationParamsWithTimeout(timeout time.Duration) *BillingAgreementsRegistrationParams {
	return &BillingAgreementsRegistrationParams{
		timeout: timeout,
	}
}

// NewBillingAgreementsRegistrationParamsWithContext creates a new BillingAgreementsRegistrationParams object
// with the ability to set a context for a request.
func NewBillingAgreementsRegistrationParamsWithContext(ctx context.Context) *BillingAgreementsRegistrationParams {
	return &BillingAgreementsRegistrationParams{
		Context: ctx,
	}
}

// NewBillingAgreementsRegistrationParamsWithHTTPClient creates a new BillingAgreementsRegistrationParams object
// with the ability to set a custom HTTPClient for a request.
func NewBillingAgreementsRegistrationParamsWithHTTPClient(client *http.Client) *BillingAgreementsRegistrationParams {
	return &BillingAgreementsRegistrationParams{
		HTTPClient: client,
	}
}

/*
BillingAgreementsRegistrationParams contains all the parameters to send to the API endpoint

	for the billing agreements registration operation.

	Typically these are written to a http.Request.
*/
type BillingAgreementsRegistrationParams struct {

	// CreateBillingAgreement.
	CreateBillingAgreement BillingAgreementsRegistrationBody

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the billing agreements registration params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *BillingAgreementsRegistrationParams) WithDefaults() *BillingAgreementsRegistrationParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the billing agreements registration params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *BillingAgreementsRegistrationParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the billing agreements registration params
func (o *BillingAgreementsRegistrationParams) WithTimeout(timeout time.Duration) *BillingAgreementsRegistrationParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the billing agreements registration params
func (o *BillingAgreementsRegistrationParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the billing agreements registration params
func (o *BillingAgreementsRegistrationParams) WithContext(ctx context.Context) *BillingAgreementsRegistrationParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the billing agreements registration params
func (o *BillingAgreementsRegistrationParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the billing agreements registration params
func (o *BillingAgreementsRegistrationParams) WithHTTPClient(client *http.Client) *BillingAgreementsRegistrationParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the billing agreements registration params
func (o *BillingAgreementsRegistrationParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithCreateBillingAgreement adds the createBillingAgreement to the billing agreements registration params
func (o *BillingAgreementsRegistrationParams) WithCreateBillingAgreement(createBillingAgreement BillingAgreementsRegistrationBody) *BillingAgreementsRegistrationParams {
	o.SetCreateBillingAgreement(createBillingAgreement)
	return o
}

// SetCreateBillingAgreement adds the createBillingAgreement to the billing agreements registration params
func (o *BillingAgreementsRegistrationParams) SetCreateBillingAgreement(createBillingAgreement BillingAgreementsRegistrationBody) {
	o.CreateBillingAgreement = createBillingAgreement
}

// WriteToRequest writes these params to a swagger request
func (o *BillingAgreementsRegistrationParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if err := r.SetBodyParam(o.CreateBillingAgreement); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
