// Code generated by go-swagger; DO NOT EDIT.

package manage_webhooks

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// DeleteWebhookSubscriptionReader is a Reader for the DeleteWebhookSubscription structure.
type DeleteWebhookSubscriptionReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DeleteWebhookSubscriptionReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewDeleteWebhookSubscriptionOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 401:
		result := NewDeleteWebhookSubscriptionUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewDeleteWebhookSubscriptionNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewDeleteWebhookSubscriptionInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[DELETE /notification-subscriptions/v1/webhooks/{webhookId}] deleteWebhookSubscription", response, response.Code())
	}
}

// NewDeleteWebhookSubscriptionOK creates a DeleteWebhookSubscriptionOK with default headers values
func NewDeleteWebhookSubscriptionOK() *DeleteWebhookSubscriptionOK {
	return &DeleteWebhookSubscriptionOK{}
}

/*
DeleteWebhookSubscriptionOK describes a response with status code 200, with default header values.

Ok
*/
type DeleteWebhookSubscriptionOK struct {
}

// IsSuccess returns true when this delete webhook subscription o k response has a 2xx status code
func (o *DeleteWebhookSubscriptionOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this delete webhook subscription o k response has a 3xx status code
func (o *DeleteWebhookSubscriptionOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this delete webhook subscription o k response has a 4xx status code
func (o *DeleteWebhookSubscriptionOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this delete webhook subscription o k response has a 5xx status code
func (o *DeleteWebhookSubscriptionOK) IsServerError() bool {
	return false
}

// IsCode returns true when this delete webhook subscription o k response a status code equal to that given
func (o *DeleteWebhookSubscriptionOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the delete webhook subscription o k response
func (o *DeleteWebhookSubscriptionOK) Code() int {
	return 200
}

func (o *DeleteWebhookSubscriptionOK) Error() string {
	return fmt.Sprintf("[DELETE /notification-subscriptions/v1/webhooks/{webhookId}][%d] deleteWebhookSubscriptionOK", 200)
}

func (o *DeleteWebhookSubscriptionOK) String() string {
	return fmt.Sprintf("[DELETE /notification-subscriptions/v1/webhooks/{webhookId}][%d] deleteWebhookSubscriptionOK", 200)
}

func (o *DeleteWebhookSubscriptionOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewDeleteWebhookSubscriptionUnauthorized creates a DeleteWebhookSubscriptionUnauthorized with default headers values
func NewDeleteWebhookSubscriptionUnauthorized() *DeleteWebhookSubscriptionUnauthorized {
	return &DeleteWebhookSubscriptionUnauthorized{}
}

/*
DeleteWebhookSubscriptionUnauthorized describes a response with status code 401, with default header values.

Unauthorized
*/
type DeleteWebhookSubscriptionUnauthorized struct {
}

// IsSuccess returns true when this delete webhook subscription unauthorized response has a 2xx status code
func (o *DeleteWebhookSubscriptionUnauthorized) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this delete webhook subscription unauthorized response has a 3xx status code
func (o *DeleteWebhookSubscriptionUnauthorized) IsRedirect() bool {
	return false
}

// IsClientError returns true when this delete webhook subscription unauthorized response has a 4xx status code
func (o *DeleteWebhookSubscriptionUnauthorized) IsClientError() bool {
	return true
}

// IsServerError returns true when this delete webhook subscription unauthorized response has a 5xx status code
func (o *DeleteWebhookSubscriptionUnauthorized) IsServerError() bool {
	return false
}

// IsCode returns true when this delete webhook subscription unauthorized response a status code equal to that given
func (o *DeleteWebhookSubscriptionUnauthorized) IsCode(code int) bool {
	return code == 401
}

// Code gets the status code for the delete webhook subscription unauthorized response
func (o *DeleteWebhookSubscriptionUnauthorized) Code() int {
	return 401
}

func (o *DeleteWebhookSubscriptionUnauthorized) Error() string {
	return fmt.Sprintf("[DELETE /notification-subscriptions/v1/webhooks/{webhookId}][%d] deleteWebhookSubscriptionUnauthorized", 401)
}

func (o *DeleteWebhookSubscriptionUnauthorized) String() string {
	return fmt.Sprintf("[DELETE /notification-subscriptions/v1/webhooks/{webhookId}][%d] deleteWebhookSubscriptionUnauthorized", 401)
}

func (o *DeleteWebhookSubscriptionUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewDeleteWebhookSubscriptionNotFound creates a DeleteWebhookSubscriptionNotFound with default headers values
func NewDeleteWebhookSubscriptionNotFound() *DeleteWebhookSubscriptionNotFound {
	return &DeleteWebhookSubscriptionNotFound{}
}

/*
DeleteWebhookSubscriptionNotFound describes a response with status code 404, with default header values.

Not found
*/
type DeleteWebhookSubscriptionNotFound struct {
}

// IsSuccess returns true when this delete webhook subscription not found response has a 2xx status code
func (o *DeleteWebhookSubscriptionNotFound) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this delete webhook subscription not found response has a 3xx status code
func (o *DeleteWebhookSubscriptionNotFound) IsRedirect() bool {
	return false
}

// IsClientError returns true when this delete webhook subscription not found response has a 4xx status code
func (o *DeleteWebhookSubscriptionNotFound) IsClientError() bool {
	return true
}

// IsServerError returns true when this delete webhook subscription not found response has a 5xx status code
func (o *DeleteWebhookSubscriptionNotFound) IsServerError() bool {
	return false
}

// IsCode returns true when this delete webhook subscription not found response a status code equal to that given
func (o *DeleteWebhookSubscriptionNotFound) IsCode(code int) bool {
	return code == 404
}

// Code gets the status code for the delete webhook subscription not found response
func (o *DeleteWebhookSubscriptionNotFound) Code() int {
	return 404
}

func (o *DeleteWebhookSubscriptionNotFound) Error() string {
	return fmt.Sprintf("[DELETE /notification-subscriptions/v1/webhooks/{webhookId}][%d] deleteWebhookSubscriptionNotFound", 404)
}

func (o *DeleteWebhookSubscriptionNotFound) String() string {
	return fmt.Sprintf("[DELETE /notification-subscriptions/v1/webhooks/{webhookId}][%d] deleteWebhookSubscriptionNotFound", 404)
}

func (o *DeleteWebhookSubscriptionNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewDeleteWebhookSubscriptionInternalServerError creates a DeleteWebhookSubscriptionInternalServerError with default headers values
func NewDeleteWebhookSubscriptionInternalServerError() *DeleteWebhookSubscriptionInternalServerError {
	return &DeleteWebhookSubscriptionInternalServerError{}
}

/*
DeleteWebhookSubscriptionInternalServerError describes a response with status code 500, with default header values.

Server error
*/
type DeleteWebhookSubscriptionInternalServerError struct {
}

// IsSuccess returns true when this delete webhook subscription internal server error response has a 2xx status code
func (o *DeleteWebhookSubscriptionInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this delete webhook subscription internal server error response has a 3xx status code
func (o *DeleteWebhookSubscriptionInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this delete webhook subscription internal server error response has a 4xx status code
func (o *DeleteWebhookSubscriptionInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this delete webhook subscription internal server error response has a 5xx status code
func (o *DeleteWebhookSubscriptionInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this delete webhook subscription internal server error response a status code equal to that given
func (o *DeleteWebhookSubscriptionInternalServerError) IsCode(code int) bool {
	return code == 500
}

// Code gets the status code for the delete webhook subscription internal server error response
func (o *DeleteWebhookSubscriptionInternalServerError) Code() int {
	return 500
}

func (o *DeleteWebhookSubscriptionInternalServerError) Error() string {
	return fmt.Sprintf("[DELETE /notification-subscriptions/v1/webhooks/{webhookId}][%d] deleteWebhookSubscriptionInternalServerError", 500)
}

func (o *DeleteWebhookSubscriptionInternalServerError) String() string {
	return fmt.Sprintf("[DELETE /notification-subscriptions/v1/webhooks/{webhookId}][%d] deleteWebhookSubscriptionInternalServerError", 500)
}

func (o *DeleteWebhookSubscriptionInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
