// Code generated by go-swagger; DO NOT EDIT.

package plans

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewDeactivatePlanParams creates a new DeactivatePlanParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewDeactivatePlanParams() *DeactivatePlanParams {
	return &DeactivatePlanParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewDeactivatePlanParamsWithTimeout creates a new DeactivatePlanParams object
// with the ability to set a timeout on a request.
func NewDeactivatePlanParamsWithTimeout(timeout time.Duration) *DeactivatePlanParams {
	return &DeactivatePlanParams{
		timeout: timeout,
	}
}

// NewDeactivatePlanParamsWithContext creates a new DeactivatePlanParams object
// with the ability to set a context for a request.
func NewDeactivatePlanParamsWithContext(ctx context.Context) *DeactivatePlanParams {
	return &DeactivatePlanParams{
		Context: ctx,
	}
}

// NewDeactivatePlanParamsWithHTTPClient creates a new DeactivatePlanParams object
// with the ability to set a custom HTTPClient for a request.
func NewDeactivatePlanParamsWithHTTPClient(client *http.Client) *DeactivatePlanParams {
	return &DeactivatePlanParams{
		HTTPClient: client,
	}
}

/*
DeactivatePlanParams contains all the parameters to send to the API endpoint

	for the deactivate plan operation.

	Typically these are written to a http.Request.
*/
type DeactivatePlanParams struct {

	/* ID.

	   Plan Id
	*/
	ID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the deactivate plan params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *DeactivatePlanParams) WithDefaults() *DeactivatePlanParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the deactivate plan params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *DeactivatePlanParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the deactivate plan params
func (o *DeactivatePlanParams) WithTimeout(timeout time.Duration) *DeactivatePlanParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the deactivate plan params
func (o *DeactivatePlanParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the deactivate plan params
func (o *DeactivatePlanParams) WithContext(ctx context.Context) *DeactivatePlanParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the deactivate plan params
func (o *DeactivatePlanParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the deactivate plan params
func (o *DeactivatePlanParams) WithHTTPClient(client *http.Client) *DeactivatePlanParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the deactivate plan params
func (o *DeactivatePlanParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the deactivate plan params
func (o *DeactivatePlanParams) WithID(id string) *DeactivatePlanParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the deactivate plan params
func (o *DeactivatePlanParams) SetID(id string) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *DeactivatePlanParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
