// Code generated by go-swagger; DO NOT EDIT.

package plans

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"encoding/json"
	"fmt"
	"io"
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// GetPlanCodeReader is a Reader for the GetPlanCode structure.
type GetPlanCodeReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetPlanCodeReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetPlanCodeOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewGetPlanCodeBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 502:
		result := NewGetPlanCodeBadGateway()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[GET /rbs/v1/plans/code] getPlanCode", response, response.Code())
	}
}

// NewGetPlanCodeOK creates a GetPlanCodeOK with default headers values
func NewGetPlanCodeOK() *GetPlanCodeOK {
	return &GetPlanCodeOK{}
}

/*
GetPlanCodeOK describes a response with status code 200, with default header values.

Successful response.
*/
type GetPlanCodeOK struct {
	Payload *GetPlanCodeOKBody
}

// IsSuccess returns true when this get plan code o k response has a 2xx status code
func (o *GetPlanCodeOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this get plan code o k response has a 3xx status code
func (o *GetPlanCodeOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get plan code o k response has a 4xx status code
func (o *GetPlanCodeOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this get plan code o k response has a 5xx status code
func (o *GetPlanCodeOK) IsServerError() bool {
	return false
}

// IsCode returns true when this get plan code o k response a status code equal to that given
func (o *GetPlanCodeOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the get plan code o k response
func (o *GetPlanCodeOK) Code() int {
	return 200
}

func (o *GetPlanCodeOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /rbs/v1/plans/code][%d] getPlanCodeOK %s", 200, payload)
}

func (o *GetPlanCodeOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /rbs/v1/plans/code][%d] getPlanCodeOK %s", 200, payload)
}

func (o *GetPlanCodeOK) GetPayload() *GetPlanCodeOKBody {
	return o.Payload
}

func (o *GetPlanCodeOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(GetPlanCodeOKBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetPlanCodeBadRequest creates a GetPlanCodeBadRequest with default headers values
func NewGetPlanCodeBadRequest() *GetPlanCodeBadRequest {
	return &GetPlanCodeBadRequest{}
}

/*
GetPlanCodeBadRequest describes a response with status code 400, with default header values.

Invalid request.
*/
type GetPlanCodeBadRequest struct {
	Payload *GetPlanCodeBadRequestBody
}

// IsSuccess returns true when this get plan code bad request response has a 2xx status code
func (o *GetPlanCodeBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get plan code bad request response has a 3xx status code
func (o *GetPlanCodeBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get plan code bad request response has a 4xx status code
func (o *GetPlanCodeBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this get plan code bad request response has a 5xx status code
func (o *GetPlanCodeBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this get plan code bad request response a status code equal to that given
func (o *GetPlanCodeBadRequest) IsCode(code int) bool {
	return code == 400
}

// Code gets the status code for the get plan code bad request response
func (o *GetPlanCodeBadRequest) Code() int {
	return 400
}

func (o *GetPlanCodeBadRequest) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /rbs/v1/plans/code][%d] getPlanCodeBadRequest %s", 400, payload)
}

func (o *GetPlanCodeBadRequest) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /rbs/v1/plans/code][%d] getPlanCodeBadRequest %s", 400, payload)
}

func (o *GetPlanCodeBadRequest) GetPayload() *GetPlanCodeBadRequestBody {
	return o.Payload
}

func (o *GetPlanCodeBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(GetPlanCodeBadRequestBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetPlanCodeBadGateway creates a GetPlanCodeBadGateway with default headers values
func NewGetPlanCodeBadGateway() *GetPlanCodeBadGateway {
	return &GetPlanCodeBadGateway{}
}

/*
GetPlanCodeBadGateway describes a response with status code 502, with default header values.

Unexpected system error or system timeout.
*/
type GetPlanCodeBadGateway struct {
	Payload *GetPlanCodeBadGatewayBody
}

// IsSuccess returns true when this get plan code bad gateway response has a 2xx status code
func (o *GetPlanCodeBadGateway) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get plan code bad gateway response has a 3xx status code
func (o *GetPlanCodeBadGateway) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get plan code bad gateway response has a 4xx status code
func (o *GetPlanCodeBadGateway) IsClientError() bool {
	return false
}

// IsServerError returns true when this get plan code bad gateway response has a 5xx status code
func (o *GetPlanCodeBadGateway) IsServerError() bool {
	return true
}

// IsCode returns true when this get plan code bad gateway response a status code equal to that given
func (o *GetPlanCodeBadGateway) IsCode(code int) bool {
	return code == 502
}

// Code gets the status code for the get plan code bad gateway response
func (o *GetPlanCodeBadGateway) Code() int {
	return 502
}

func (o *GetPlanCodeBadGateway) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /rbs/v1/plans/code][%d] getPlanCodeBadGateway %s", 502, payload)
}

func (o *GetPlanCodeBadGateway) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /rbs/v1/plans/code][%d] getPlanCodeBadGateway %s", 502, payload)
}

func (o *GetPlanCodeBadGateway) GetPayload() *GetPlanCodeBadGatewayBody {
	return o.Payload
}

func (o *GetPlanCodeBadGateway) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(GetPlanCodeBadGatewayBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

/*
GetPlanCodeBadGatewayBody get plan code bad gateway body
swagger:model GetPlanCodeBadGatewayBody
*/
type GetPlanCodeBadGatewayBody struct {

	// The detail message related to the status and reason listed above.
	Message string `json:"message,omitempty"`

	// The reason of the status.
	//
	// Possible values:
	//  - SYSTEM_ERROR
	//  - SERVER_TIMEOUT
	//  - SERVICE_TIMEOUT
	//
	Reason string `json:"reason,omitempty"`

	// The status of the submitted transaction.
	//
	// Possible values:
	//  - SERVER_ERROR
	//
	Status string `json:"status,omitempty"`

	// Time of request in UTC. Format: `YYYY-MM-DDThh:mm:ssZ`
	// **Example** `2016-08-11T22:47:57Z` equals August 11, 2016, at 22:47:57 (10:47:57 p.m.).
	// The `T` separates the date and the time. The `Z` indicates UTC.
	//
	// Returned by Cybersource for all services.
	//
	SubmitTimeUtc string `json:"submitTimeUtc,omitempty"`
}

// Validate validates this get plan code bad gateway body
func (o *GetPlanCodeBadGatewayBody) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this get plan code bad gateway body based on context it is used
func (o *GetPlanCodeBadGatewayBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *GetPlanCodeBadGatewayBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *GetPlanCodeBadGatewayBody) UnmarshalBinary(b []byte) error {
	var res GetPlanCodeBadGatewayBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}

/*
GetPlanCodeBadRequestBody get plan code bad request body
swagger:model GetPlanCodeBadRequestBody
*/
type GetPlanCodeBadRequestBody struct {

	// details
	Details []*GetPlanCodeBadRequestBodyDetailsItems0 `json:"details"`

	// The detail message related to the status and reason listed above.
	Message string `json:"message,omitempty"`

	// The reason of the status.
	//
	// Possible values:
	//  - MISSING_FIELD
	//  - INVALID_DATA
	//  - DUPLICATE_REQUEST
	//  - INVALID_MERCHANT_CONFIGURATION
	//
	Reason string `json:"reason,omitempty"`

	// The status of the submitted transaction.
	//
	// Possible values:
	//  - INVALID_REQUEST
	//
	Status string `json:"status,omitempty"`

	// Time of request in UTC. Format: `YYYY-MM-DDThh:mm:ssZ`
	// **Example** `2016-08-11T22:47:57Z` equals August 11, 2016, at 22:47:57 (10:47:57 p.m.).
	// The `T` separates the date and the time. The `Z` indicates UTC.
	//
	// Returned by Cybersource for all services.
	//
	SubmitTimeUtc string `json:"submitTimeUtc,omitempty"`
}

// Validate validates this get plan code bad request body
func (o *GetPlanCodeBadRequestBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateDetails(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *GetPlanCodeBadRequestBody) validateDetails(formats strfmt.Registry) error {
	if swag.IsZero(o.Details) { // not required
		return nil
	}

	for i := 0; i < len(o.Details); i++ {
		if swag.IsZero(o.Details[i]) { // not required
			continue
		}

		if o.Details[i] != nil {
			if err := o.Details[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("getPlanCodeBadRequest" + "." + "details" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("getPlanCodeBadRequest" + "." + "details" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// ContextValidate validate this get plan code bad request body based on the context it is used
func (o *GetPlanCodeBadRequestBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := o.contextValidateDetails(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *GetPlanCodeBadRequestBody) contextValidateDetails(ctx context.Context, formats strfmt.Registry) error {

	for i := 0; i < len(o.Details); i++ {

		if o.Details[i] != nil {

			if swag.IsZero(o.Details[i]) { // not required
				return nil
			}

			if err := o.Details[i].ContextValidate(ctx, formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("getPlanCodeBadRequest" + "." + "details" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("getPlanCodeBadRequest" + "." + "details" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (o *GetPlanCodeBadRequestBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *GetPlanCodeBadRequestBody) UnmarshalBinary(b []byte) error {
	var res GetPlanCodeBadRequestBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}

/*
GetPlanCodeBadRequestBodyDetailsItems0 get plan code bad request body details items0
swagger:model GetPlanCodeBadRequestBodyDetailsItems0
*/
type GetPlanCodeBadRequestBodyDetailsItems0 struct {

	// This is the flattened JSON object field name/path that is either missing or invalid.
	Field string `json:"field,omitempty"`

	// Possible reasons for the error.
	//
	// Possible values:
	//  - MISSING_FIELD
	//  - INVALID_DATA
	//
	Reason string `json:"reason,omitempty"`
}

// Validate validates this get plan code bad request body details items0
func (o *GetPlanCodeBadRequestBodyDetailsItems0) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this get plan code bad request body details items0 based on context it is used
func (o *GetPlanCodeBadRequestBodyDetailsItems0) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *GetPlanCodeBadRequestBodyDetailsItems0) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *GetPlanCodeBadRequestBodyDetailsItems0) UnmarshalBinary(b []byte) error {
	var res GetPlanCodeBadRequestBodyDetailsItems0
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}

/*
GetPlanCodeOKBody getPlanCodeResponse
swagger:model GetPlanCodeOKBody
*/
type GetPlanCodeOKBody struct {

	// Plan code
	//
	// Max Length: 10
	Code string `json:"code,omitempty"`

	// Time of request in UTC. Format: `YYYY-MM-DDThh:mm:ssZ`
	// **Example** `2016-08-11T22:47:57Z` equals August 11, 2016, at 22:47:57 (10:47:57 p.m.).
	// The `T` separates the date and the time. The `Z` indicates UTC.
	//
	// Returned by Cybersource for all services.
	//
	SubmitTimeUtc string `json:"submitTimeUtc,omitempty"`
}

// Validate validates this get plan code o k body
func (o *GetPlanCodeOKBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateCode(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *GetPlanCodeOKBody) validateCode(formats strfmt.Registry) error {
	if swag.IsZero(o.Code) { // not required
		return nil
	}

	if err := validate.MaxLength("getPlanCodeOK"+"."+"code", "body", o.Code, 10); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this get plan code o k body based on context it is used
func (o *GetPlanCodeOKBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *GetPlanCodeOKBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *GetPlanCodeOKBody) UnmarshalBinary(b []byte) error {
	var res GetPlanCodeOKBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
