// Code generated by go-swagger; DO NOT EDIT.

package transient_token_data

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// GetPaymentCredentialsForTransientTokenReader is a Reader for the GetPaymentCredentialsForTransientToken structure.
type GetPaymentCredentialsForTransientTokenReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetPaymentCredentialsForTransientTokenReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetPaymentCredentialsForTransientTokenOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 404:
		result := NewGetPaymentCredentialsForTransientTokenNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewGetPaymentCredentialsForTransientTokenInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[GET /up/v1/payment-credentials/{jti}] getPaymentCredentialsForTransientToken", response, response.Code())
	}
}

// NewGetPaymentCredentialsForTransientTokenOK creates a GetPaymentCredentialsForTransientTokenOK with default headers values
func NewGetPaymentCredentialsForTransientTokenOK() *GetPaymentCredentialsForTransientTokenOK {
	return &GetPaymentCredentialsForTransientTokenOK{}
}

/*
GetPaymentCredentialsForTransientTokenOK describes a response with status code 200, with default header values.

Retrieved payment credentials reference
*/
type GetPaymentCredentialsForTransientTokenOK struct {
	Payload string
}

// IsSuccess returns true when this get payment credentials for transient token o k response has a 2xx status code
func (o *GetPaymentCredentialsForTransientTokenOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this get payment credentials for transient token o k response has a 3xx status code
func (o *GetPaymentCredentialsForTransientTokenOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get payment credentials for transient token o k response has a 4xx status code
func (o *GetPaymentCredentialsForTransientTokenOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this get payment credentials for transient token o k response has a 5xx status code
func (o *GetPaymentCredentialsForTransientTokenOK) IsServerError() bool {
	return false
}

// IsCode returns true when this get payment credentials for transient token o k response a status code equal to that given
func (o *GetPaymentCredentialsForTransientTokenOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the get payment credentials for transient token o k response
func (o *GetPaymentCredentialsForTransientTokenOK) Code() int {
	return 200
}

func (o *GetPaymentCredentialsForTransientTokenOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /up/v1/payment-credentials/{jti}][%d] getPaymentCredentialsForTransientTokenOK %s", 200, payload)
}

func (o *GetPaymentCredentialsForTransientTokenOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /up/v1/payment-credentials/{jti}][%d] getPaymentCredentialsForTransientTokenOK %s", 200, payload)
}

func (o *GetPaymentCredentialsForTransientTokenOK) GetPayload() string {
	return o.Payload
}

func (o *GetPaymentCredentialsForTransientTokenOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetPaymentCredentialsForTransientTokenNotFound creates a GetPaymentCredentialsForTransientTokenNotFound with default headers values
func NewGetPaymentCredentialsForTransientTokenNotFound() *GetPaymentCredentialsForTransientTokenNotFound {
	return &GetPaymentCredentialsForTransientTokenNotFound{}
}

/*
GetPaymentCredentialsForTransientTokenNotFound describes a response with status code 404, with default header values.

The specified resource not found in the system.
*/
type GetPaymentCredentialsForTransientTokenNotFound struct {
}

// IsSuccess returns true when this get payment credentials for transient token not found response has a 2xx status code
func (o *GetPaymentCredentialsForTransientTokenNotFound) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get payment credentials for transient token not found response has a 3xx status code
func (o *GetPaymentCredentialsForTransientTokenNotFound) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get payment credentials for transient token not found response has a 4xx status code
func (o *GetPaymentCredentialsForTransientTokenNotFound) IsClientError() bool {
	return true
}

// IsServerError returns true when this get payment credentials for transient token not found response has a 5xx status code
func (o *GetPaymentCredentialsForTransientTokenNotFound) IsServerError() bool {
	return false
}

// IsCode returns true when this get payment credentials for transient token not found response a status code equal to that given
func (o *GetPaymentCredentialsForTransientTokenNotFound) IsCode(code int) bool {
	return code == 404
}

// Code gets the status code for the get payment credentials for transient token not found response
func (o *GetPaymentCredentialsForTransientTokenNotFound) Code() int {
	return 404
}

func (o *GetPaymentCredentialsForTransientTokenNotFound) Error() string {
	return fmt.Sprintf("[GET /up/v1/payment-credentials/{jti}][%d] getPaymentCredentialsForTransientTokenNotFound", 404)
}

func (o *GetPaymentCredentialsForTransientTokenNotFound) String() string {
	return fmt.Sprintf("[GET /up/v1/payment-credentials/{jti}][%d] getPaymentCredentialsForTransientTokenNotFound", 404)
}

func (o *GetPaymentCredentialsForTransientTokenNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewGetPaymentCredentialsForTransientTokenInternalServerError creates a GetPaymentCredentialsForTransientTokenInternalServerError with default headers values
func NewGetPaymentCredentialsForTransientTokenInternalServerError() *GetPaymentCredentialsForTransientTokenInternalServerError {
	return &GetPaymentCredentialsForTransientTokenInternalServerError{}
}

/*
GetPaymentCredentialsForTransientTokenInternalServerError describes a response with status code 500, with default header values.

Unexpected server error
*/
type GetPaymentCredentialsForTransientTokenInternalServerError struct {
}

// IsSuccess returns true when this get payment credentials for transient token internal server error response has a 2xx status code
func (o *GetPaymentCredentialsForTransientTokenInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get payment credentials for transient token internal server error response has a 3xx status code
func (o *GetPaymentCredentialsForTransientTokenInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get payment credentials for transient token internal server error response has a 4xx status code
func (o *GetPaymentCredentialsForTransientTokenInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this get payment credentials for transient token internal server error response has a 5xx status code
func (o *GetPaymentCredentialsForTransientTokenInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this get payment credentials for transient token internal server error response a status code equal to that given
func (o *GetPaymentCredentialsForTransientTokenInternalServerError) IsCode(code int) bool {
	return code == 500
}

// Code gets the status code for the get payment credentials for transient token internal server error response
func (o *GetPaymentCredentialsForTransientTokenInternalServerError) Code() int {
	return 500
}

func (o *GetPaymentCredentialsForTransientTokenInternalServerError) Error() string {
	return fmt.Sprintf("[GET /up/v1/payment-credentials/{jti}][%d] getPaymentCredentialsForTransientTokenInternalServerError", 500)
}

func (o *GetPaymentCredentialsForTransientTokenInternalServerError) String() string {
	return fmt.Sprintf("[GET /up/v1/payment-credentials/{jti}][%d] getPaymentCredentialsForTransientTokenInternalServerError", 500)
}

func (o *GetPaymentCredentialsForTransientTokenInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
